# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 07:06
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20160425_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_form', to='home.FormPage'),
        ),
    ]
