# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 07:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_contactpage_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_form', to='home.ContactPage'),
        ),
    ]
