# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_contactpage_thank_you_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='page',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_form', to='home.FormPage'),
        ),
    ]
